#!/usr/bin/env ruby

# David Selassie
# hashcolor

# Takes this computer's mac address and username and makes it into a color triad.

require 'rubygems'
require 'color'
require './colorfix'
require 'macaddr'
require 'digest'
require 'trollop'

opts = Trollop::options do
  opt :format, 'Output format ("sh" or "el")', :default => 'sh'
  opt :mac, 'Force a MAC address', :default => Mac::address
  opt :user, 'Force a username', :default => ENV['USER']
  opt :saturation, 'Saturation', :default => 100.0
  opt :lightness, 'Lightness', :default => 70.0
  opt :angle, 'Angle', :default => 20.0
end

# How far off complementary the second two hues h2, h3 are.
angle = opts[:angle]
saturation = opts[:saturation]
lightness = opts[:lightness]

# Find the main hue.
h1 = Digest::MD5.hexdigest(opts[:mac] + opts[:user]).to_i(16) + 90
# This needs to be an integer to work sensibly:
h1 = h1 % 360
# Make a angle triad.
h2 = (h1 + 180.0 - angle) % 360.0
h3 = (h1 + 180.0 + angle) % 360.0

c1 = Color::HSL.new(h1, saturation, lightness)
c2 = Color::HSL.new(h2, saturation, lightness)
c3 = Color::HSL.new(h3, saturation, lightness)

if opts[:format] == 'sh' then
  puts "# Made with colorhash from user #{opts[:user]} and MAC #{opts[:mac]}"
  puts "# http://github.com/selassid/hashcolor"
  puts 'export C1="\[\033[38;5;' + c1.to_xterm.to_s + 'm\]"'
  puts 'export C2="\[\033[38;5;' + c2.to_xterm.to_s + 'm\]"'
  puts 'export C3="\[\033[38;5;' + c3.to_xterm.to_s + 'm\]"'
  puts 'export NC="\[\033[0m\]"'
elsif opts[:format] == 'el' then
  puts "; Made with colorhash from user #{opts[:user]} and MAC #{opts[:mac]}"
  puts "; http://github.com/selassid/hashcolor"
  puts "(defvar colorhash-1 \"#{c1.html}\")"
  puts "(defvar colorhash-2 \"#{c2.html}\")"
  puts "(defvar colorhash-3 \"#{c3.html}\")"
end
